import re
import json
from urllib.parse import urljoin


class StreamInfo:
    def __init__(self, url, headers=None):
        self.url = url
        self.headers = headers or {}

    def __repr__(self):
        return f"StreamInfo(url={self.url[:80]}..., headers={self.headers})"


class StreamResolver:
    def __init__(self, html, page_url, log=None):
        self.html = html
        self.page_url = page_url
        self.log = log or (lambda msg: None)

    def resolve(self):
        extractors = [
            ("inline JS var/player.src()", self._find_inline_js_vars),
            ("Video.js / hls.js config object", self._find_video_js_config),
            ("direct .m3u8 in HTML", self._find_direct_m3u8),
            ("data-* attributes", self._find_data_attributes),
            ("JSON inside script tags", self._find_in_json_script),
            ("playlist URL patterns", self._find_playlist_url),
        ]

        for label, method in extractors:
            result = method()
            if result:
                self.log(f"[Streams] ✓ {label}: {result.url[:80]}...")
                return result
            self.log(f"[Streams] ✗ {label} — no match")

        blob_urls = re.findall(r'blob:https?://[^"\')\s;]+', self.html)
        if blob_urls:
            self.log("[Streams] ⚠ Only blob: URLs found (not usable from Kodi)")
            self.log(f"[Streams]   First blob: {blob_urls[0][:80]}")
            self.log("[Streams]   The actual .m3u8 is likely generated by JS.")
            self.log("[Streams]   Open devtools → Network tab → filter .m3u8 to find the real URL.")

        raise Exception("Could not find HLS stream URL in channel page")

    def _find_direct_m3u8(self):
        m = re.search(
            r'(https?://[^"\'<>\[\]\s]+\.m3u8[^"\'<>\[\]\s]*)',
            self.html
        )
        if m:
            url = m.group(1).strip()
            full = urljoin(self.page_url, url)
            if full.startswith("http"):
                return StreamInfo(full)
        return None

    def _find_inline_js_vars(self):
        patterns = [
            r'(?:var|let|const)\s+(?:streamUrl|stream_url|videoUrl|video_url|src|m3u8)\s*[=:]\s*["\']([^"\']+\.m3u8[^"\']*)["\']',
            r'player\.src\(\s*["\']([^"\']+\.m3u8[^"\']*)["\']',
            r'player\.src\(\s*\{\s*["\']?src["\']?\s*:\s*["\']([^"\']+\.m3u8[^"\']*)["\']',
            r'setAttribute\(["\']src["\']\s*,\s*["\']([^"\']+\.m3u8[^"\']*)["\']',
        ]
        for p in patterns:
            m = re.search(p, self.html)
            if m:
                return StreamInfo(urljoin(self.page_url, m.group(1)))
        return None

    def _find_video_js_config(self):
        patterns = [
            r'["\'](?:file|src)["\']\s*:\s*["\']([^"\']+\.m3u8[^"\']*)["\']',
            r'["\'](?:file|src)["\']\s*:\s*["\']([^"\']+)["\'].*?m3u8',
        ]
        for p in patterns:
            m = re.search(p, self.html, re.DOTALL)
            if m:
                val = m.group(1)
                if val.startswith("http") and ".m3u8" in val:
                    return StreamInfo(val)
                if ".m3u8" in val:
                    return StreamInfo(urljoin(self.page_url, val))
        return None

    def _find_data_attributes(self):
        patterns = [
            r'data-(?:url|src|stream|video|hls)[^=]*=["\']([^"\']+\.m3u8[^"\']*)["\']',
            r'data-[\w-]+=["\']([^"\']+\.m3u8[^"\']*)["\']',
        ]
        for p in patterns:
            m = re.search(p, self.html)
            if m:
                return StreamInfo(urljoin(self.page_url, m.group(1)))
        return None

    def _find_in_json_script(self):
        for m in re.finditer(
            r'<script[^>]*type=["\']application/json["\'][^>]*>(.*?)</script>',
            self.html, re.DOTALL | re.IGNORECASE
        ):
            try:
                data = json.loads(m.group(1))
                result = self._search_json_for_url(data)
                if result:
                    return result
            except json.JSONDecodeError:
                continue

        for m in re.finditer(
            r'<script[^>]*>[^<]*\bvar\s+\w+\s*=\s*({.*?})\s*;</script>',
            self.html, re.DOTALL
        ):
            try:
                data = json.loads(m.group(1))
                result = self._search_json_for_url(data)
                if result:
                    return result
            except (json.JSONDecodeError, ValueError):
                continue
        return None

    def _search_json_for_url(self, obj, depth=0):
        if depth > 5:
            return None
        if isinstance(obj, str):
            if ".m3u8" in obj and obj.startswith("http"):
                return StreamInfo(obj)
            return None
        if isinstance(obj, dict):
            for key in ("url", "src", "file", "stream", "manifest", "playlist", "source", "sources"):
                val = obj.get(key)
                if isinstance(val, str) and ".m3u8" in val:
                    full = urljoin(self.page_url, val)
                    if full.startswith("http"):
                        return StreamInfo(full)
                if isinstance(val, (dict, list)):
                    result = self._search_json_for_url(val, depth + 1)
                    if result:
                        return result
            for val in obj.values():
                if isinstance(val, (dict, list)):
                    result = self._search_json_for_url(val, depth + 1)
                    if result:
                        return result
        if isinstance(obj, list):
            for item in obj:
                result = self._search_json_for_url(item, depth + 1)
                if result:
                    return result
        return None

    def _find_playlist_url(self):
        patterns = [
            r'(https?://[^"\'<>]+/playlist[^"\'<>]*)',
            r'(https?://[^"\'<>]+/manifest[^"\'<>]*)',
            r'(https?://[^"\'<>]+/m3u8[^"\'<>]*)',
            r'(https?://[^"\'<>]+\.m3u8)',
        ]
        for p in patterns:
            m = re.search(p, self.html, re.IGNORECASE)
            if m:
                url = m.group(1)
                if url.startswith("http"):
                    return StreamInfo(url)
        return None
